-- tests/run.lua
-- Offline tests for the pure domain code. No FiveM needed:
--     cd spz-progression && lua tests/run.lua
-- (or via Python: python tests/run_lupa.py)
--
-- vectors.lua is generated by Docs/report-v3/make_figs.py from the reference
-- formula in the design report, so a pass here means the Lua matches the
-- document.

SPZ = {}
Config = nil
local base = (TEST_BASE or ".") .. "/"
dofile(base .. "config.lua")
dofile(base .. "domain/rank.lua")
dofile(base .. "domain/rp.lua")
dofile(base .. "domain/irating.lua")
dofile(base .. "domain/sr.lua")

local R    = Config.Rules
local Rows = SPZ.Rank.BuildTable(R)
local pass, fail = 0, 0

local function check(name, cond, detail)
    if cond then pass = pass + 1
    else fail = fail + 1; print("FAIL  " .. name .. (detail and ("  " .. detail) or "")) end
end

-- ── Golden vectors ─────────────────────────────────────────────────────────
local vectors = dofile(base .. "tests/vectors.lua")
for i, v in ipairs(vectors) do
    local got = SPZ.RP.Compute({
        position = v.pos, n = v.n, rp = v.rp, fieldAvg = v.fieldAvg, dnf = v.dnf,
        clean = v.clean, streak = v.streak, perfectLap = v.flat >= 10,
        trackRecord = v.flat >= 20,
    }, R)
    check("vector " .. i, got == v.expect, ("got %d expected %d"):format(got, v.expect))
end

-- ── Rank table ─────────────────────────────────────────────────────────────
check("20 rungs", #Rows == 20)
check("For(0) = C-5", SPZ.Rank.For(0, Rows) == "C-5")
check("For(249) = C-1", SPZ.Rank.For(249, Rows) == "C-1")
check("For(250) = B-5", SPZ.Rank.For(250, Rows) == "B-5")
check("For(1150) = A-5", SPZ.Rank.For(1150, Rows) == "A-5")
check("For(7850) = S-1", SPZ.Rank.For(7850, Rows) == "S-1")
check("For(999999) = S-1", SPZ.Rank.For(999999, Rows) == "S-1")
local _, tier = SPZ.Rank.For(3850, Rows)
check("tier of 3850 = 3", tier == 3)
-- the legacy bug: rank never left -5. Every rung must be reachable.
local seen = {}
for rp = 0, 9000, 5 do seen[SPZ.Rank.For(rp, Rows)] = true end
local count = 0 for _ in pairs(seen) do count = count + 1 end
check("all 20 ranks reachable", count == 20, tostring(count))
local prev = 0
for rp = 0, 9000, 7 do
    local _, t = SPZ.Rank.For(rp, Rows)
    local idx = 0
    for i, r in ipairs(Rows) do if rp >= r.rp then idx = i end end
    check("monotonic " .. rp, idx >= prev); prev = idx
end
check("floor(260) = 250", SPZ.Rank.ClassFloor(260, R) == 250)
check("floor(4000) = 3850", SPZ.Rank.ClassFloor(4000, R) == 3850)
check("compare up", SPZ.Rank.Compare("C-5", "C-4", Rows) == 1)
check("compare down", SPZ.Rank.Compare("B-3", "B-4", Rows) == -1)
local frac, nxt = SPZ.Rank.Progress(275, Rows)
check("progress 275", nxt == "B-4" and math.abs(frac - 25 / 180) < 1e-9)

-- ── RP properties ──────────────────────────────────────────────────────────
check("solo pays nothing", SPZ.RP.Compute({ position = 1, n = 1, rp = 0, fieldAvg = 0 }, R) == 0)
for _, n in ipairs({ 2, 3, 5, 8, 16, 30, 64, 200, 1000, 100000 }) do
    local last = math.huge
    local set, list = {}, {}
    for _, pos in ipairs({ 1, 2, 3, 4, math.max(1, n // 2), n }) do
        if pos <= n and not set[pos] then set[pos] = true; list[#list + 1] = pos end
    end
    table.sort(list)
    for _, pos in ipairs(list) do
        do
            local d = SPZ.RP.Compute({ position = pos, n = n, rp = 0, fieldAvg = 0 }, R)
            check(("bounds N=%d P%d"):format(n, pos), d >= -19 and d <= 51, tostring(d))
            check(("monotonic N=%d P%d"):format(n, pos), d <= last, tostring(d)); last = d
        end
    end
end
check("podium 0 at N=8", SPZ.RP.Podium(1, 8, false, R) == 0)
check("podium full at N=24", SPZ.RP.Podium(1, 24, false, R) == 10)
check("podium full at N=500", SPZ.RP.Podium(2, 500, false, R) == 6)
check("podium none for DNF", SPZ.RP.Podium(1, 64, true, R) == 0)
check("streak top 8", SPZ.RP.StreakTop(8, R) == 3)
check("streak top 30", SPZ.RP.StreakTop(30, R) == 3)
check("streak top 64", SPZ.RP.StreakTop(64, R) == 7)
check("streak top 200", SPZ.RP.StreakTop(200, R) == 20)

-- floor + daily cap
local d, after = SPZ.RP.Apply(260, -40, 250, 0, R)
check("rank lock", after == 250 and d == -10)
d, after = SPZ.RP.Apply(100, 50, 0, 280, R)
check("daily cap", d == 20 and after == 120)
d, after = SPZ.RP.Apply(100, 50, 0, 300, R)
check("daily cap reached", d == 0 and after == 100)
d, after = SPZ.RP.Apply(100, -10, 0, 300, R)
check("losses after cap", d == -10)

-- ── iRating: zero-sum, no change alone ─────────────────────────────────────
local field = {}
for i = 1, 8 do field[i] = { key = i, rating = 1300 + i * 50, position = i, dnf = (i == 8) } end
local deltas = SPZ.IRating.Deltas(field, Config.IRating)
local sum = 0 for _, v in pairs(deltas) do sum = sum + v end
check("iRating near zero-sum", math.abs(sum) <= 4, tostring(sum))
check("iRating winner gains", deltas[1] > 0)
check("iRating DNF loses", deltas[8] < 0)
local solo = SPZ.IRating.Deltas({ { key = "a", rating = 1500, position = 1 } }, Config.IRating)
check("iRating solo = 0", solo.a == 0)

-- ── SR daily caps ──────────────────────────────────────────────────────────
local sr, applied, day = SPZ.SR.Apply(2.0, 0.15, { gain = 0.45, loss = 0, marker = 10 }, 10, Config.SR)
check("SR gain cap", math.abs(applied - 0.05) < 1e-9 and math.abs(sr - 2.05) < 1e-9, tostring(applied))
sr, applied, day = SPZ.SR.Apply(2.0, 0.15, { gain = 0.45, loss = 0, marker = 9 }, 10, Config.SR)
check("SR cap resets next day", math.abs(applied - 0.15) < 1e-9 and day.gain == 0.15)
sr, applied = SPZ.SR.Apply(2.0, -0.20, { gain = 0, loss = -0.30, marker = 10 }, 10, Config.SR)
check("SR loss cap", math.abs(applied + 0.10) < 1e-9, tostring(applied))
check("SR clean P1", math.abs(SPZ.SR.Delta({ position = 1, incidents = 0 }, Config.SR) - 0.15) < 1e-9)

print(("%d passed, %d failed"):format(pass, fail))
if fail > 0 then error("tests failed") end
